"""empty message

Revision ID: 867a8ad08b73
Revises: 
Create Date: 2018-02-01 18:02:02.751782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867a8ad08b73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('account', sa.String(length=25), nullable=False),
    sa.Column('passward', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
